name: "Tests"

on:
  pull_request: # Workflow only runs for PR against main

jobs:
  test-general:
    name: "conda-vendor tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: "Checkout condan-vendor"
        uses: actions/checkout@main
      - name: "Install  conda dependencies"
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: conda-vendor-dependencies
          environment-file: environment.yaml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          pip install .
          pytest -vvv
